#!/usr/bin/env python3
"""
xc8_asm_revelator_v4_0.py

Smarter conservative XC8/PIC assembly/listing review tool, v4.0.

Reads Microchip XC8 / PIC-AS .lst, .s, or .asm files and produces a programmer-focused
Markdown report, JSON report, and optionally an annotated listing. It does not blindly
rewrite code. It explains what the emitted assembly appears to do and where a human
should inspect possible inefficiency.

Python 3.9+, no third-party dependencies.
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

KNOWN_MNEMONICS = {
    # enhanced midrange PIC instruction set + common pseudo/directives
    "addlw","addwf","andlw","andwf","asrf","bcf","bra","brw","bsf","btfsc","btfss",
    "call","clrc","clrf","clrw","clrwdt","comf","cpfseq","cpfsgt","cpfslt","decf","decfsz",
    "goto","incf","incfsz","iorlw","iorwf","lslf","lsrf","movf","movlb","movlp","movlw",
    "movwf","nop","option","pagesel","psect","reset","retfie","retlw","return","rlf","rrf",
    "setc","sleep","sublw","subwf","swapf","tris","xorlw","xorwf","ljmp","fcall",
    # directives / pseudo ops
    "processor","pagewidth","opt","dabs","equ","set","global","extrn","org","end","dw","db","de",
    "config","radix","space","align","class","section",
}
BRANCHES = {"goto", "bra", "ljmp"}
CALLS = {"call", "fcall"}
RETURNS = {"return", "retlw", "retfie"}
SKIPS = {"btfsc", "btfss", "decfsz", "incfsz", "cpfseq", "cpfsgt", "cpfslt"}
BANK_SELECTS = {"movlb", "banksel"}
BARRIERS = BRANCHES | CALLS | RETURNS | {"psect", "org", "end", "global", "section"}
DIRECTIVES = {"processor","pagewidth","opt","dabs","equ","set","global","extrn","org","end","dw","db","de","config","radix","space","align","class","section","psect"}
FILE_REGISTER_OPS = {
    "clrf","movwf","movf","bcf","bsf","rlf","rrf","swapf","andwf","iorwf","xorwf",
    "addwf","subwf","decf","incf","decfsz","incfsz","btfsc","btfss","cpfseq","cpfsgt","cpfslt","lslf","lsrf","asrf"
}

def rough_cycles(mnemonic: Optional[str], operands: str = "") -> Tuple[float, str]:
    if not mnemonic:
        return 0.0, "not an instruction"
    m = mnemonic.lower()
    if m in DIRECTIVES:
        return 0.0, "directive/pseudo-op"
    if m in BRANCHES or m in CALLS or m in RETURNS:
        return 2.0, "control transfer, usually 2 cycles on midrange PICs"
    if m in SKIPS:
        return 1.5, "skip-class instruction; cost depends on whether the skip is taken"
    return 1.0, "ordinary single-cycle instruction estimate"

@dataclasses.dataclass
class AsmLine:
    physical_line: int
    raw: str
    list_line: Optional[int] = None
    address: Optional[int] = None
    address_text: str = ""
    opcode_text: str = ""
    asm_text: str = ""
    code: str = ""
    comment: str = ""
    label: Optional[str] = None
    mnemonic: Optional[str] = None
    operands: str = ""
    psect: Optional[str] = None
    source_ref: Optional[str] = None

    def is_instruction(self) -> bool:
        return self.mnemonic is not None and self.mnemonic not in DIRECTIVES

@dataclasses.dataclass
class Finding:
    severity: str
    category: str
    line: int
    message: str
    why: str
    suggestion: str
    raw: str
    parsed: str = ""
    source_ref: Optional[str] = None
    address: str = ""
    related_lines: List[int] = dataclasses.field(default_factory=list)
    context: List[str] = dataclasses.field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)

# -----------------------------------------------------------------------------
# Parsing Architecture
# -----------------------------------------------------------------------------

def split_comment(s: str) -> Tuple[str, str]:
    if ";" in s:
        a, b = s.split(";", 1)
        return a.rstrip(), ";" + b.rstrip()
    return s.rstrip(), ""

def hex_to_int(s: str) -> Optional[int]:
    try:
        return int(s, 16)
    except ValueError:
        return None

def parse_line(n: int, raw: str, current_psect: Optional[str], last_source_ref: Optional[str]) -> AsmLine:
    line = raw.rstrip("\n")
    out = AsmLine(physical_line=n, raw=line, psect=current_psect, source_ref=last_source_ref)
    s = line.rstrip()

    if not s.strip():
        return out

    # Capture source reference lines generated by compiler
    msrc = re.search(r";\s*([^;]*\.(?:c|h|s|asm)):\s*(\d+)\s*:\s*(.*)$", s, re.I)
    if msrc:
        out.comment = s.strip()
        out.source_ref = f"{msrc.group(1).strip()}:{msrc.group(2)}: {msrc.group(3).strip()}"
        return out

    # Refined Listing Separator Pipeline
    m = re.match(r"^\s*(\d+)\s+([0-9A-Fa-f]{4,6})?\s*((?:[0-9A-Fa-f]{4}(?:\s+[0-9A-Fa-f]{4})*))?\s*(.*)$", s)
    candidate = s.strip()
    if m:
        out.list_line = int(m.group(1))
        if m.group(2):
            out.address_text = m.group(2).upper()
            out.address = hex_to_int(m.group(2))
        if m.group(3):
            out.opcode_text = " ".join(m.group(3).split())
        candidate = (m.group(4) or "").strip()

    if not candidate or candidate.startswith("!"):
        if candidate.startswith("!"):
            out.comment = candidate
        return out

    code, comment = split_comment(candidate)
    out.asm_text = candidate
    out.code = code
    out.comment = comment
    stripped = code.strip()
    if not stripped:
        return out

    # Handle Labels with explicit trailing match protections
    lm = re.match(r"^([A-Za-z_.$?][\w.$?@#]*):\s*(.*)$", stripped)
    rest = stripped
    if lm:
        out.label = lm.group(1)
        rest = lm.group(2).strip()

    if rest:
        parts = rest.split(None, 1)
        tok = parts[0].lower()
        if tok in KNOWN_MNEMONICS:
            out.mnemonic = tok
            out.operands = parts[1].strip() if len(parts) > 1 else ""
            if tok == "psect":
                out.psect = out.operands.split(",", 1)[0].strip()
    return out

def parse_file(path: Path) -> List[AsmLine]:
    raw_lines = path.read_text(errors="replace").splitlines()
    out: List[AsmLine] = []
    current_psect: Optional[str] = None
    last_source_ref: Optional[str] = None
    for i, raw in enumerate(raw_lines, 1):
        ln = parse_line(i, raw, current_psect, last_source_ref)
        if ln.source_ref and not (ln.mnemonic or ln.label):
            last_source_ref = ln.source_ref
        if ln.mnemonic == "psect":
            current_psect = ln.psect
        else:
            ln.psect = current_psect
        if ln.mnemonic or ln.label:
            ln.source_ref = last_source_ref
        out.append(ln)
    return out

# -----------------------------------------------------------------------------
# Analysis Subsystem
# -----------------------------------------------------------------------------

def normalize_symbol(op: str) -> str:
    if not op:
        return ""
    first = op.split(",", 1)[0].strip()
    first = first.replace("BANKMASK(", "").replace(")", "")
    return first.lstrip("#").strip()

def target_label(op: str) -> str:
    return normalize_symbol(op)

def label_map(lines: List[AsmLine]) -> Dict[str, int]:
    return {ln.label: i for i, ln in enumerate(lines) if ln.label}

def next_code(lines: List[AsmLine], i: int) -> Optional[int]:
    for j in range(i + 1, len(lines)):
        if lines[j].mnemonic or lines[j].label:
            return j
    return None

def prev_code(lines: List[AsmLine], i: int) -> Optional[int]:
    for j in range(i - 1, -1, -1):
        if lines[j].mnemonic or lines[j].label:
            return j
    return None

def line_window(lines: List[AsmLine], i: int, radius: int = 3) -> List[str]:
    lo = max(0, i - radius)
    hi = min(len(lines), i + radius + 1)
    rows = []
    for k in range(lo, hi):
        ln = lines[k]
        if ln.mnemonic or ln.label:
            pointer = "=>" if k == i else "  "
            rows.append(f"{pointer} {ln.physical_line}: {ln.asm_text or ln.raw.strip()}")
    return rows

def reg_display(name_or_num: str, sfr_by_addr: Dict[int, List[str]]) -> str:
    x = name_or_num.strip()
    if re.fullmatch(r"\d+", x):
        n = int(x)
        names = sfr_by_addr.get(n)
        if names:
            return f"{x} ({'/'.join(names[:3])})"
    return x

def operand_display_for(mnemonic: Optional[str], operands: str, sfr_by_addr: Dict[int, List[str]]) -> str:
    parts = [p.strip() for p in operands.split(",")]
    if mnemonic in FILE_REGISTER_OPS and parts:
        parts[0] = reg_display(parts[0], sfr_by_addr)
    return ", ".join(parts)

class Analyzer:
    def __init__(self, lines: List[AsmLine], focus: str = "program"):
        self.lines = lines
        self.focus = focus
        self.labels = label_map(lines)
        self.findings: List[Finding] = []
        self.sfr_by_addr, self.addr_by_sfr = self.extract_symbols()
        self.program_indices = self.compute_program_indices()

    def extract_symbols(self) -> Tuple[Dict[int, List[str]], Dict[str, int]]:
        by_addr: Dict[int, List[str]] = defaultdict(list)
        by_name: Dict[str, int] = {}
        for ln in self.lines:
            text = ln.asm_text or ln.raw
            m = re.match(r"\s*([A-Za-z_][\w$]*)\s+(equ|set)\s+([0-9A-Fa-fx]+|\d+)\b", text, re.I)
            if m:
                name = m.group(1)
                val_s = m.group(3)
                try:
                    val = int(val_s, 0) if val_s.lower().startswith("0x") else int(val_s)
                except ValueError:
                    try:
                        val = int(val_s, 16)
                    except ValueError:
                        continue
                if len(by_addr[val]) < 12:
                    by_addr[val].append(name)
                by_name[name] = val
        return dict(by_addr), by_name

    def compute_program_indices(self) -> List[int]:
        idx = []
        in_maintext = False
        for i, ln in enumerate(self.lines):
            if ln.mnemonic == "psect":
                ps = ln.operands.split(",", 1)[0].strip().lower()
                in_maintext = ps in {"maintext", "text", "reset_vec", "cinit"} or "text" in ps
            if self.focus == "all":
                if ln.mnemonic or ln.label:
                    idx.append(i)
            elif self.focus == "maintext":
                if in_maintext and (ln.mnemonic or ln.label):
                    idx.append(i)
            else:
                if (ln.mnemonic or ln.label) and (in_maintext or ln.mnemonic not in {"equ", "set"}):
                    idx.append(i)
        return idx

    def add(self, sev: str, cat: str, i: int, msg: str, why: str, sug: str, related: Optional[List[int]] = None):
        ln = self.lines[i]
        parsed = ln.asm_text or ln.code or ln.raw.strip()
        if ln.mnemonic and ln.operands:
            parsed = f"{ln.mnemonic} {operand_display_for(ln.mnemonic, ln.operands, self.sfr_by_addr)}"
        self.findings.append(Finding(
            severity=sev, category=cat, line=ln.physical_line, message=msg, why=why,
            suggestion=sug, raw=ln.raw, parsed=parsed, source_ref=ln.source_ref,
            address=ln.address_text, related_lines=related or [], context=line_window(self.lines, i)
        ))

    def analyze(self) -> List[Finding]:
        self.find_nops()
        self.find_banks()
        self.find_branches()
        self.find_delay_loops()
        self.find_movlw_patterns()
        self.find_status_tests()
        self.find_call_patterns()
        return sorted(self.findings, key=lambda f: (f.line, f.category))

    def consider(self, i: int) -> bool:
        return i in self.program_indices

    def find_nops(self):
        for i, ln in enumerate(self.lines):
            if ln.mnemonic != "nop" or not self.consider(i):
                continue
            p = prev_code(self.lines, i)
            n = next_code(self.lines, i)
            pm = self.lines[p].mnemonic if p is not None else None
            nm = self.lines[n].mnemonic if n is not None else None
            if pm in SKIPS:
                self.add("INFO", "NOP_AFTER_SKIP", i, "NOP follows a skip-class instruction.", "A NOP after DECFSZ/BTFSS/etc. is often deliberate single-instruction padding.", "Usually keep. It may be part of exact timing or skip balancing.", [self.lines[p].physical_line] if p else [])
            elif pm in BRANCHES or pm in RETURNS:
                self.add("WARN", "NOP_AFTER_CONTROL_TRANSFER", i, "NOP follows an unconditional control transfer.", "Normal execution usually cannot fall through to this NOP.", "Inspect whether this is padding, delay-loop residue, or a branch target. Remove only if not timing-relevant.", [self.lines[p].physical_line] if p else [])
            elif nm in RETURNS:
                self.add("WARN", "NOP_BEFORE_RETURN", i, "NOP immediately precedes a return.", "This usually costs one cycle unless deliberately inserted.", "Check timing intent. If not needed, remove at source/asm level.", [self.lines[n].physical_line] if n else [])
            else:
                self.add("INFO", "NOP_GENERAL", i, "NOP instruction found.", "May be timing padding, alignment, or compiler residue.", "Review in context; do not remove blindly.")

    def find_banks(self):
        last: Optional[Tuple[str, str, int]] = None
        for i, ln in enumerate(self.lines):
            if not self.consider(i) or not ln.mnemonic:
                continue
            if ln.label or ln.mnemonic in BARRIERS:
                last = None  # Clear context state across sequence junctions
                if ln.mnemonic in BARRIERS:
                    continue
            if ln.mnemonic in BANK_SELECTS:
                op = normalize_symbol(ln.operands)
                if last and last[0] == ln.mnemonic and last[1] == op:
                    self.add("WARN", "REPEATED_BANK_SELECT", i, f"Repeated {ln.mnemonic.upper()} {op}.", "Repeated bank selects can be compiler conservatism, but are sometimes required after uncertain control flow.", "If no label/call/branch can enter between the two, the later bank select may be removable.", [self.lines[last[2]].physical_line])
                last = (ln.mnemonic, op, i)

    def find_branches(self):
        for i, ln in enumerate(self.lines):
            if not self.consider(i) or ln.mnemonic not in BRANCHES:
                continue
            tgt = target_label(ln.operands)
            if tgt and tgt in self.labels:
                ni = next_code(self.lines, i)
                if ni is not None and self.lines[ni].label == tgt:
                    self.add("STRONG", "BRANCH_TO_NEXT_LABEL", i, f"{ln.mnemonic.upper()} goes to the next label {tgt}.", "A branch to the very next executable location usually wastes cycles and code space.", "Remove only if not needed for psect/debug/linker artifact.", [self.lines[ni].physical_line])
                if self.labels[tgt] == i or self.lines[i].label == tgt:
                    self.add("WARN", "SELF_BRANCH", i, f"{ln.mnemonic.upper()} appears to branch to itself.", "This is an idle/error trap pattern or a bug.", "Keep for deliberate halt loops only.", [self.lines[self.labels[tgt]].physical_line])
            p = prev_code(self.lines, i)
            if p is not None and self.lines[p].mnemonic in SKIPS:
                n = next_code(self.lines, i)
                if n is not None and self.lines[n].mnemonic in BRANCHES:
                    self.add("INFO", "SKIP_WITH_DOUBLE_GOTO", p, "Skip instruction feeds a two-GOTO decision pattern.", "XC8 often implements if/else as skip + goto + goto. Correct, but not always compact.", "For tiny code, inspect whether source logic can be rearranged so the fall-through path is the common path.", [self.lines[i].physical_line, self.lines[n].physical_line])

    def find_delay_loops(self):
        for i, ln in enumerate(self.lines):
            if not self.consider(i) or not ln.label:
                continue
            window = []
            j = i
            for _ in range(10):
                j = next_code(self.lines, j)
                if j is None:
                    break
                window.append(j)
            if not window:
                continue
            mn = [self.lines[k].mnemonic for k in window]
            jumps_back = [k for k in window if self.lines[k].mnemonic in BRANCHES and target_label(self.lines[k].operands) == ln.label]
            if any(m in {"decfsz", "incfsz"} for m in mn) and jumps_back:
                self.add("INFO", "DELAY_LOOP", i, f"Label '{ln.label}' appears to start a delay/timing loop.", "Counter/skip/branch loop detected. This is commonly generated for __delay_ms/us style delays.", "If timing is not critical, consider a hardware timer or cooperative wait. If timing is critical, keep it but document the oscillator assumption.", [self.lines[k].physical_line for k in window[:8]])

    def find_movlw_patterns(self):
        last: Optional[Tuple[str, int]] = None
        for i, ln in enumerate(self.lines):
            if not self.consider(i) or not ln.mnemonic:
                continue
            if ln.label or ln.mnemonic in BARRIERS:
                last = None
            if ln.mnemonic == "movlw":
                val = ln.operands.strip()
                if last and last[0] == val:
                    self.add("WARN", "REPEATED_MOVLW", i, f"MOVLW reloads literal {val} already loaded earlier.", "Reloading W with the same literal may be redundant if W was not consumed/clobbered.", "Inspect intervening instructions. If W was still valid, source may be forcing repeated loads.", [self.lines[last[1]].physical_line])
                last = (val, i)
            elif ln.mnemonic in {"addlw", "andlw", "iorlw", "xorlw", "sublw", "movf"}:
                last = None

    def find_status_tests(self):
        for i, ln in enumerate(self.lines):
            if not self.consider(i) or ln.mnemonic not in {"btfss", "btfsc"}:
                continue
            ops = [p.strip() for p in ln.operands.split(",")]
            if len(ops) >= 2 and ops[0] in {"3", "STATUS", "status"}:
                if ops[1] == "2":
                    self.add("INFO", "STATUS_Z_TEST", i, "Code tests STATUS,Z after arithmetic/logical work.", "This is the normal PIC way to implement comparisons such as == 0.", "Useful marker: inspect the previous one or two instructions to understand the C condition being implemented.")

    def find_call_patterns(self):
        calls = []
        current = None
        graph = defaultdict(list)
        line_of = {}
        for i, ln in enumerate(self.lines):
            if not self.consider(i):
                continue
            if ln.label:
                current = ln.label
                line_of[current] = ln.physical_line
            if ln.mnemonic in CALLS:
                tgt = target_label(ln.operands)
                calls.append((i, tgt))
                if current and tgt:
                    graph[current].append(tgt)
        counts = Counter(t for _, t in calls if t)
        for tgt, c in counts.items():
            if c >= 5:
                ls = [self.lines[idx].physical_line for idx, t in calls if t == tgt][:10]
                self.add("INFO", "HOT_CALL_TARGET", calls[0][0], f"Function '{tgt}' is called {c} times.", "Frequent calls to tiny functions may cost more than the work they perform.", "Inspect whether this helper should be inline or simplified.", ls)
        for a, tgts in graph.items():
            if a in tgts:
                for idx, t in calls:
                    if t == a:
                        self.add("WARN", "SELF_CALL", idx, f"Function/label '{a}' appears to call itself.", "PIC hardware return stacks are shallow; recursion is usually dangerous.", "Verify this is not accidental recursion.", [line_of.get(a, 0)])

# -----------------------------------------------------------------------------
# Report Generators & Serialization
# -----------------------------------------------------------------------------

def build_summary(lines: List[AsmLine], analyzer: Analyzer) -> Dict[str, Any]:
    rec = [ln for ln in lines if ln.mnemonic or ln.label]
    instr = [ln for ln in lines if ln.is_instruction()]
    directives = [ln for ln in lines if ln.mnemonic in DIRECTIVES]
    psects = Counter(ln.psect or "<none>" for ln in instr)
    mn = Counter(ln.mnemonic for ln in instr if ln.mnemonic)
    banks = [ln for ln in instr if ln.mnemonic in BANK_SELECTS]
    branches = [ln for ln in instr if ln.mnemonic in BRANCHES]
    skips = [ln for ln in instr if ln.mnemonic in SKIPS]
    calls = [ln for ln in instr if ln.mnemonic in CALLS]
    returns = [ln for ln in instr if ln.mnemonic in RETURNS]
    cycles = sum(rough_cycles(ln.mnemonic, ln.operands)[0] for ln in instr)
    src = Counter(ln.source_ref for ln in instr if ln.source_ref)
    return {
        "physical_lines": len(lines),
        "recognized_lines": len(rec),
        "instruction_lines": len(instr),
        "directive_lines": len(directives),
        "labels": len([ln for ln in lines if ln.label]),
        "rough_static_cycle_sum": cycles,
        "mnemonics": dict(mn.most_common()),
        "psects": dict(psects.most_common()),
        "bank_selects": len(banks),
        "branches": len(branches),
        "skips": len(skips),
        "calls": len(calls),
        "returns": len(returns),
        "source_refs": dict(src.most_common(20)),
    }

def render_report(path: Path, lines: List[AsmLine], analyzer: Analyzer, findings: List[Finding]) -> str:
    summary = build_summary(lines, analyzer)
    instr = [ln for ln in lines if ln.is_instruction()]
    rec = [ln for ln in lines if ln.mnemonic or ln.label]
    sev = Counter(f.severity for f in findings)

    meanings = {
        "movlb": "select RAM/SFR bank", "clrf": "clear register", "bcf": "clear one bit", "bsf": "set one bit",
        "movlw": "load literal into W", "movwf": "store W into register", "decfsz": "decrement and skip if zero",
        "goto": "unconditional branch", "ljmp": "long jump", "btfss": "bit test, skip if set", "btfsc": "bit test, skip if clear",
        "rlf": "rotate/shift left through carry", "andlw": "AND literal with W", "andwf": "AND W with file register", "nop": "no operation/timing padding",
        "clrc": "clear carry bit", "movf": "move/read file register, often setting flags",
    }

    out = [
        "# XC8 Assembly Programmer Review", "",
        f"**Input:** `{path}`", "",
        "## Executive summary", "",
        f"- Physical listing lines: **{summary['physical_lines']}**",
        f"- Recognized assembly/directive/label lines: **{summary['recognized_lines']}**",
        f"- Executable instruction lines: **{summary['instruction_lines']}**",
        f"- Labels: **{summary['labels']}**",
        f"- Rough static cycle sum, one pass through listed instructions: **{summary['rough_static_cycle_sum']:.1f}** cycles",
        f"- Findings: **{len(findings)}** — STRONG {sev.get('STRONG',0)}, WARN {sev.get('WARN',0)}, INFO {sev.get('INFO',0)}", "",
        "The cycle number is not runtime. Loops, branches, skips, interrupts, and oscillator setup change real timing. It is a programmer-orientation metric.", "",
        "## First recognized program lines", "", "```asm"
    ]
    for ln in rec[:30]:
        addr = f"{ln.address_text} " if ln.address_text else ""
        out.append(f"{ln.physical_line:5d}: {addr}{ln.asm_text or ln.raw.strip()}")
    
    out.extend([
        "```", 
        "", 
        "## Instruction mix", 
        "", 
        "| Mnemonic | Count | Programmer meaning |", 
        "|---|---:|---|"
    ])
    
    for m, c in Counter(ln.mnemonic for ln in instr if ln.mnemonic).most_common():
        out.append(f"| `{m}` | {c} | {meanings.get(m, 'instruction')} |")
    
    out.extend(["", "## Register/SFR interpretation", ""])
    used = []
    for ln in instr:
        if ln.operands and ln.mnemonic in FILE_REGISTER_OPS:
            first = normalize_symbol(ln.operands)
            if re.fullmatch(r"\d+", first):
                names = analyzer.sfr_by_addr.get(int(first))
                if names:
                    used.append((ln.physical_line, first, "/".join(names[:4]), ln.asm_text))
    if used:
        out.extend(["| Line | Numeric operand | Symbol meaning | Instruction |", "|---:|---:|---|---|"])
        for l, num, names, text in used[:40]:
            out.append(f"| {l} | {num} | `{names}` | `{text}` |")
    else:
        out.append("No numeric SFR operands were confidently mapped to symbols.")
        
    out.extend(["", "## Source-line map", ""])
    if summary["source_refs"]:
        out.extend(["| Source reference | Instruction count |", "|---|---:|"])
        for src, c in summary["source_refs"].items():
            out.append(f"| `{src}` | {c} |")
    else:
        out.append("No C source references were found in the parsed instruction stream.")
        
    out.extend(["", "## Findings", ""])
    if not findings:
        out.append("No suspicious patterns were detected by the current rules.")
    for f in findings:
        rel = f" Related lines: {', '.join(map(str, f.related_lines))}." if f.related_lines else ""
        out.append(f"### Line {f.line}: {f.category} [{f.severity}]")
        if f.source_ref:
            out.append(f"Source context: `{f.source_ref}`")
        if f.address:
            out.append(f"Address: `{f.address}`")
        out.extend(["", "```asm", f.raw, "```"])
        if f.parsed:
            out.append(f"Parsed / interpreted as: `{f.parsed}`")
        out.extend(["", f"**Finding:** {f.message}", "", f"**Why it matters:** {f.why}{rel}", "", f"**Suggested action:** {f.suggestion}"])
        if f.context:
            out.extend(["", "Local context:", "```asm"])
            out.extend(f.context)
            out.append("```")
        out.append("")

    out.extend([
        "## Programmer notes", "",
        "- Treat `volatile` comments as a clue that the compiler is preserving exact SFR access semantics.",
        "- `movlb` is not automatically bad; it is the price of banked memory/SFRs. Repeated `movlb` only matters when no possible entry path needs it.",
        "- Delay loops are not automatically bad; they are often exactly what `__delay_ms()` requested. They are bad only when they block useful work or depend on an undocumented oscillator assumption.",
        "- Skip + goto + goto patterns are common compiler output for tiny PIC conditionals. They are correct but sometimes source can be rearranged for a shorter fall-through path.", ""
    ])
    return "\n".join(out)

def write_annotated(lines: List[AsmLine], findings: List[Finding], path: Path):
    by = defaultdict(list)
    for f in findings:
        by[f.line].append(f)
    out = []
    for ln in lines:
        if ln.physical_line in by:
            out.append("; " + "-"*77)
            for f in by[ln.physical_line]:
                out.append(f"; REVIEW {f.severity} {f.category}: {f.message}")
                if f.source_ref:
                    out.append(f"; SOURCE: {f.source_ref}")
                if f.parsed:
                    out.append(f"; PARSED: {f.parsed}")
                out.append(f"; WHY: {f.why}")
                out.append(f"; DO: {f.suggestion}")
            out.append("; " + "-"*77)
        out.append(ln.raw)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Smarter XC8/PIC .lst/.asm programmer review tool")
    ap.add_argument("input", type=Path)
    ap.add_argument("--report", type=Path)
    ap.add_argument("--json", type=Path)
    ap.add_argument("--annotate", action="store_true")
    ap.add_argument("--annotated-output", type=Path)
    ap.add_argument("--min-severity", choices=["INFO", "WARN", "STRONG"], default="INFO")
    ap.add_argument("--focus", choices=["program", "maintext", "all"], default="program")
    args = ap.parse_args(argv)

    if not args.input.exists():
        raise SystemExit(f"Input file not found: {args.input}")

    rank = {"INFO": 0, "WARN": 1, "STRONG": 2}
    lines = parse_file(args.input)
    an = Analyzer(lines, focus=args.focus)
    findings = [f for f in an.analyze() if rank[f.severity] >= rank[args.min_severity]]
    summary = build_summary(lines, an)

    print(f"Input physical lines: {summary['physical_lines']}")
    print(f"Findings: {len(findings)}")

    rpt = args.report or args.input.with_suffix(args.input.suffix + ".programmer_review.md")
    rpt.write_text(render_report(args.input, lines, an, findings), encoding="utf-8")
    
    if args.json:
        payload = {"summary": summary, "findings": [f.to_dict() for f in findings]}
        args.json.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    if args.annotate or args.annotated_output:
        out = args.annotated_output or args.input.with_suffix(args.input.suffix + ".annotated.lst")
        write_annotated(lines, findings, out)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())